name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "django_application_packeges"
  EB_APPLICATION_NAME      : "my django"
  EB_ENVIRONMENT_NAME      : "my django-env"
  DEPLOY_PACKAGE_NAME      : "django_app_${{github.sha}}.zip"
  AWS_REGION_NAME          : "us-west-2"


on:
  push:
    branches:
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: git clone our repo
        uses: actions/checkout@v1

      - name: creat zip deployment package
        run : zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
      - name: Configure my credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{secrets.MY_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.MY_SECRET_KEY}}
          aws-region           : ${{env.AWS_REGION_NAME}}
          
      - name: copy Deployment pacage to S3 bucket
        run : aws S3 cp ${{env.DEPLOY_PACKAGE_NAME}} S3://${{env.EB_PACKAGE_S3_BUCKET_NAME}}/
        
      - name: Print happy massage for CI finish
        run : echo "CI pipline part finished successfuly"
